{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "private-repo-credentials",
    "namespace": "kommander-flux",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "private-repo-credentials",
        "namespace": "kommander-flux",
        "creationTimestamp": null
      },
      "type": "Opaque",
      "data": null
    },
    "encryptedData": {
      "password": "AgBiswC0/B4rhgLk9XHXcQnNKbW5upakzXy9qjJFt0QfuBu7amvHp3sG8GYQ6qDj19KVjY7BXUFY9sB2MVxRKQByyz+68be6fIq6Tx2Prp5rc7be62RV5/vCbrjMf+mKmT710ge1Es5LuLrM25HJZgAi8gb1u3IVto+h2lmcMHANRMR0Z2mAbvva40SnsQCNGQIJ3D+3glWbI07PWn1skTu08929E6mq/r/UgL31hQIUAE4swcZ7TjgtBEqBniqONRZevg79um2lt3dcVOGiecwe9DliKLg5HBu71MXLAkq+pUfklhuxdC+8z/Z+PqGjxd1emB120kuN081oKthwwzCXv3SMj3tAocEz/jBe74JkF9Wgh4T0CzbCg2/mEDkhTXn3btG9NOdqPagpnfqkMMimHr01g4Xx1X1OoSEw7waV8urE3ZIzfXMtjO9bmVMIjo57agvs/kQ4t3M4nk/0CNePYIotEmtczD8CUdRU4ok7XkSbbMErrpPwJvJGhcuc4Q1kDu49dR2vUE6hZdJvzs0QVTEJ2/sls6vaZRm5Ii7so/UnxJWE6veU/PPtzzbqrh3i9Nr3ofpNmoZqIikQj646j51MRH00fjMKNIywN+I1UEVQhxG9HKzvyK1OfCExsFF1pIsDgy7Wm7CiVcVvkObZKPj7HTX8DWmYBj0tL/ppaSK3TCiZVYosKAt91z7+tCKOIIGhAaS95hrz+urhwJo1CXtjx+085+X31r3ArG5O+ncPMWp92Yur",
      "username": "AgChZ+f/hyB21IUdVRvUb6v9dLyijY5tMWx7SateX0fOwdGAp1PJcbXe7P331qtuhWLRsVTjw+bzKFLnR11ZhuwDf5gPAEWPcW1yn2ZDrM1R/SSnuonbk5vQcHtcdKuwzYrwH94/ySr5Grc8W7r0ram51zsxfJQxT/hPijaxko4Ch7YvzrmWV3YF8XFtCTv56HlQgkrwT0VbJLNvqA8oZqqB9tNEbV69PxuywgqAmWemnR80z5ctukRXGnjBLI6IWbmM0wMj8iVKbzydHbk5jmQZtJISW4nlXftH+PRC/z7Oawdu6M7TesoDbB6r4EmchNkQnC24muL/PuehAo5nPTOarZg2EMjj190bUiwDlfjRRMH8tzPL0UoSPW23vmWT+Lw5X9NgjKbpAgztptuCC2xlxCQCehiingSuRaQrWFFXJJ3FKpaHXq8y2nVJuOxR+AvfOanVP7aaMjGzK1SZIMe9cLYDzMmTOgsCW248eBlcL2SlIvhrqSgjVtUx1asmTWVl+IAFwU2yljqz13M0wCTZO7fJfbHxKpJrFmKgi7RQnUfc3Sjr5NwVh/7sxWETCH8xJlpmMOa2yBGUUFofNx/pGymz+BwSVD8iqqZ4eNOZ1Rj9bTmWRius32i8t3CLIwznw1s26pBG1e1pUOCq8HoY89pvMrndjoUHCq9Sx9gc859j7Is5X/iC01gdvVo5NAymYOkYujiZxZVWoBjZKg=="
    }
  }
}
